//! Explicit, reversible Kitty integration for `dimax keys install`.
//! The generated `dimax.conf` is separate from the user's `kitty.conf`;
//! installation adds one include line, creates a one-time backup before
//! editing an existing config, and refuses to overwrite user-owned files.

use std::path::PathBuf;

/// Marker comment that opens the generated block -- present so
/// [`install`] can tell "this file is exactly what dimax would
/// generate today" apart from "the user has their own `dimax.conf`" (or
/// an older generated version) without needing a separate manifest.
const GENERATED_MARKER: &str =
    "# --- dimax: generated by `dimax keys install`, do not hand-edit ---";
const INCLUDE_LINE: &str = "include dimax.conf";

/// Render the full contents of `dimax.conf` (chords + the dedicated
/// `shift+enter` mapping -- see `keys.rs` module doc for why that one's
/// not in [`super::keys::BINDINGS`]) from the shared binding table.
#[cfg(test)]
fn render_dimax_conf() -> String {
    render_dimax_conf_with(&[])
}

pub fn render_effective_dimax_conf() -> String {
    render_dimax_conf_with(&super::keys::custom_kitty_bindings())
}

fn render_dimax_conf_with(custom: &[(String, Vec<u8>)]) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_MARKER);
    out.push('\n');
    out.push_str(
        "# dimax Cmd-chord forwarding -- lets `dimax attach` recognize Cmd-key\n\
         # chords despite terminals not normally reporting Cmd as a modifier.\n\
         # `all` sends the text regardless of kitty's current keyboard mode,\n\
         # matching how a raw-mode TUI like dimax expects every keystroke to\n\
         # arrive unmodified. See src/tui/keys.rs in the dimax repo for the\n\
         # authoritative escape-sequence table this is generated from.\n\n",
    );
    for binding in super::keys::BINDINGS {
        let tag = String::from_utf8_lossy(binding.tag);
        out.push_str(&format!(
            "map {} send_text all \\x1b_D{}\\x1b\\\\\n",
            binding.kitty, tag
        ));
    }
    if !custom.is_empty() {
        out.push_str("\n# User-defined aliases from dimax keybindings.json\n");
        for (combo, tag) in custom {
            let tag = String::from_utf8_lossy(tag);
            out.push_str(&format!(
                "map {combo} send_text all \\x1b_D{tag}\\x1b\\\\\n"
            ));
        }
    }
    out.push_str(
        "\n# Lets the attach menu's spawn field tell Enter and Shift+Enter apart\n\
         # (otherwise both send the same \\r byte).\n\
         map shift+enter send_text all \\x1b_Ds\\x1b\\\\\n",
    );
    out
}

/// Kitty's config directory: `$KITTY_CONFIG_DIRECTORY` if the user has
/// overridden it, else the documented default `~/.config/kitty`.
fn kitty_config_dir() -> anyhow::Result<PathBuf> {
    if let Some(dir) = std::env::var_os("KITTY_CONFIG_DIRECTORY") {
        return Ok(PathBuf::from(dir));
    }
    let home = std::env::var_os("HOME").ok_or_else(|| {
        anyhow::anyhow!("could not resolve Kitty config directory: HOME is unset")
    })?;
    Ok(PathBuf::from(home).join(".config").join("kitty"))
}

fn write_atomic(path: &std::path::Path, contents: &str) -> anyhow::Result<()> {
    let temporary = path.with_extension("dimax.tmp");
    std::fs::write(&temporary, contents)?;
    std::fs::rename(temporary, path)?;
    Ok(())
}

pub fn install() -> anyhow::Result<PathBuf> {
    let config_dir = kitty_config_dir()?;
    std::fs::create_dir_all(&config_dir)?;
    let dimax_conf = config_dir.join("dimax.conf");
    let kitty_conf = config_dir.join("kitty.conf");

    let is_ours = match std::fs::read_to_string(&dimax_conf) {
        Ok(existing) => existing.starts_with(GENERATED_MARKER),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => true,
        Err(e) => return Err(e.into()),
    };
    if !is_ours {
        anyhow::bail!(
            "{} already exists and is not managed by dimax",
            dimax_conf.display()
        );
    }
    write_atomic(&dimax_conf, &render_effective_dimax_conf())?;

    let mut kitty_conf_text = match std::fs::read_to_string(&kitty_conf) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(error) => return Err(error.into()),
    };
    if !kitty_conf_text
        .lines()
        .any(|line| line.trim() == INCLUDE_LINE)
    {
        if kitty_conf.exists() {
            let backup = config_dir.join("kitty.conf.dimax.bak");
            if !backup.exists() {
                std::fs::copy(&kitty_conf, backup)?;
            }
        }
        if !kitty_conf_text.is_empty() && !kitty_conf_text.ends_with('\n') {
            kitty_conf_text.push('\n');
        }
        kitty_conf_text.push_str(INCLUDE_LINE);
        kitty_conf_text.push('\n');
        write_atomic(&kitty_conf, &kitty_conf_text)?;
    }
    Ok(dimax_conf)
}

pub fn uninstall() -> anyhow::Result<()> {
    let config_dir = kitty_config_dir()?;
    let dimax_conf = config_dir.join("dimax.conf");
    let kitty_conf = config_dir.join("kitty.conf");

    if let Ok(existing) = std::fs::read_to_string(&dimax_conf) {
        if !existing.starts_with(GENERATED_MARKER) {
            anyhow::bail!("refusing to remove user-owned {}", dimax_conf.display());
        }
        std::fs::remove_file(&dimax_conf)?;
    }

    if let Ok(existing) = std::fs::read_to_string(&kitty_conf) {
        let filtered = existing
            .lines()
            .filter(|line| line.trim() != INCLUDE_LINE)
            .collect::<Vec<_>>()
            .join("\n");
        let normalized = if filtered.is_empty() {
            String::new()
        } else {
            format!("{filtered}\n")
        };
        if normalized != existing {
            write_atomic(&kitty_conf, &normalized)?;
        }
    }
    Ok(())
}

pub fn reload() -> anyhow::Result<()> {
    let status = std::process::Command::new("kitty")
        .args(["@", "load-config"])
        .status()
        .map_err(|error| anyhow::anyhow!("could not run `kitty @ load-config`: {error}"))?;
    if !status.success() {
        anyhow::bail!(
            "`kitty @ load-config` exited with {status}; enable Kitty remote control or reload manually"
        );
    }
    Ok(())
}

pub fn ensure_config_written() -> anyhow::Result<PathBuf> {
    install()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Serializes every test in this module that mutates
    /// `KITTY_WINDOW_ID`/`KITTY_CONFIG_DIRECTORY` -- both are
    /// process-global, so two such tests running concurrently (the
    /// default under `cargo test`) could otherwise stomp on each
    /// other's env state mid-test.
    static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    /// `render_dimax_conf`'s output must actually round-trip through
    /// `keys::parse` for every chord byte in [`keys::BINDINGS`] -- catches the
    /// exact class of bug this module exists to prevent: the generated
    /// config and the parser silently drifting apart.
    #[test]
    fn render_dimax_conf_produces_chords_keys_parse_recognizes() {
        let rendered = render_dimax_conf();
        for binding in super::super::keys::BINDINGS {
            let tag = String::from_utf8_lossy(binding.tag);
            let expected_line = format!(
                "map {} send_text all \\x1b_D{}\\x1b\\\\",
                binding.kitty, tag
            );
            assert!(
                rendered.contains(&expected_line),
                "missing or malformed line for {}: {rendered}",
                binding.kitty
            );

            let bytes = [b"\x1b_D".as_slice(), binding.tag, b"\x1b\\".as_slice()].concat();
            assert_ne!(
                super::super::keys::parse(&bytes),
                super::super::Action::PassThrough,
                "chord for {} (tag {}) isn't recognized by keys::parse",
                binding.kitty,
                tag
            );
        }
    }

    #[test]
    fn render_dimax_conf_includes_the_shift_enter_mapping() {
        let rendered = render_dimax_conf();
        assert!(rendered.contains("map shift+enter send_text all \\x1b_Ds\\x1b\\\\"));
    }

    #[test]
    fn render_dimax_conf_starts_with_the_generated_marker() {
        assert!(render_dimax_conf().starts_with(GENERATED_MARKER));
    }

    fn setup_fake_kitty_config(
        dir: &std::path::Path,
        kitty_conf_body: Option<&str>,
        dimax_conf_body: Option<&str>,
    ) {
        std::fs::create_dir_all(dir).unwrap();
        if let Some(body) = kitty_conf_body {
            std::fs::write(dir.join("kitty.conf"), body).unwrap();
        }
        if let Some(body) = dimax_conf_body {
            std::fs::write(dir.join("dimax.conf"), body).unwrap();
        }
    }

    /// Runs `ensure_config_written` against a fake config directory by
    /// setting `KITTY_WINDOW_ID` and `KITTY_CONFIG_DIRECTORY` for the
    /// duration of `f`, then restoring both -- these tests can't run
    /// concurrently with each other (env vars are process-global), so
    /// each acquires this process-wide mutex first. `unsafe` is required
    /// for `set_var`/`remove_var` themselves (Rust 2024 edition); safe in
    /// practice because the mutex serializes every caller.
    fn with_fake_kitty_env<T>(config_dir: &std::path::Path, f: impl FnOnce() -> T) -> T {
        let _guard = ENV_LOCK.lock().unwrap();
        let prev_window_id = std::env::var_os("KITTY_WINDOW_ID");
        let prev_config_dir = std::env::var_os("KITTY_CONFIG_DIRECTORY");
        unsafe {
            std::env::set_var("KITTY_WINDOW_ID", "1");
            std::env::set_var("KITTY_CONFIG_DIRECTORY", config_dir);
        }
        let result = f();
        unsafe {
            match prev_window_id {
                Some(v) => std::env::set_var("KITTY_WINDOW_ID", v),
                None => std::env::remove_var("KITTY_WINDOW_ID"),
            }
            match prev_config_dir {
                Some(v) => std::env::set_var("KITTY_CONFIG_DIRECTORY", v),
                None => std::env::remove_var("KITTY_CONFIG_DIRECTORY"),
            }
        }
        result
    }

    #[test]
    fn install_creates_a_minimal_kitty_conf_when_none_exists() {
        let dir = std::env::temp_dir().join(format!("dmx-kitty-test-{}", std::process::id() + 1));
        setup_fake_kitty_config(&dir, None, None);

        with_fake_kitty_env(&dir, || ensure_config_written().unwrap());

        assert!(dir.join("dimax.conf").exists());
        assert_eq!(
            std::fs::read_to_string(dir.join("kitty.conf")).unwrap(),
            "include dimax.conf\n"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ensure_installed_writes_dimax_conf_and_patches_kitty_conf() {
        let dir = std::env::temp_dir().join(format!("dmx-kitty-test-{}", std::process::id() + 2));
        setup_fake_kitty_config(&dir, Some("# my existing config\nfont_size 12\n"), None);

        with_fake_kitty_env(&dir, || ensure_config_written().unwrap());

        let dimax_conf = std::fs::read_to_string(dir.join("dimax.conf")).unwrap();
        assert!(dimax_conf.starts_with(GENERATED_MARKER));
        assert!(dimax_conf.contains("map cmd+shift+z"));

        let kitty_conf = std::fs::read_to_string(dir.join("kitty.conf")).unwrap();
        assert!(
            kitty_conf.contains("font_size 12"),
            "existing content must be preserved"
        );
        assert!(kitty_conf.lines().any(|l| l.trim() == "include dimax.conf"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ensure_config_written_returns_the_dimax_conf_path() {
        let dir =
            std::env::temp_dir().join(format!("dmx-kitty-config-path-{}", std::process::id()));
        setup_fake_kitty_config(&dir, Some(""), None);
        let path = with_fake_kitty_env(&dir, || ensure_config_written().unwrap());
        assert_eq!(path, dir.join("dimax.conf"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ensure_installed_does_not_duplicate_the_include_line_on_a_second_run() {
        let dir = std::env::temp_dir().join(format!("dmx-kitty-test-{}", std::process::id() + 3));
        setup_fake_kitty_config(&dir, Some("# my config\n"), None);

        with_fake_kitty_env(&dir, || {
            ensure_config_written().unwrap();
            ensure_config_written().unwrap();
        });

        let kitty_conf = std::fs::read_to_string(dir.join("kitty.conf")).unwrap();
        let include_count = kitty_conf
            .lines()
            .filter(|l| l.trim() == "include dimax.conf")
            .count();
        assert_eq!(
            include_count, 1,
            "the include line must not be duplicated across repeated runs"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ensure_installed_refreshes_a_previously_generated_dimax_conf() {
        let dir = std::env::temp_dir().join(format!("dmx-kitty-test-{}", std::process::id() + 4));
        let stale_generated =
            format!("{GENERATED_MARKER}\nmap cmd+1 send_text all \\x1b_D1\\x1b\\\\\n");
        setup_fake_kitty_config(&dir, Some("include dimax.conf\n"), Some(&stale_generated));

        with_fake_kitty_env(&dir, || ensure_config_written().unwrap());

        let dimax_conf = std::fs::read_to_string(dir.join("dimax.conf")).unwrap();
        assert!(
            dimax_conf.contains("map cmd+shift+z"),
            "should have been regenerated with the full current table"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ensure_installed_never_overwrites_a_hand_written_dimax_conf() {
        let dir = std::env::temp_dir().join(format!("dmx-kitty-test-{}", std::process::id() + 5));
        let hand_written =
            "# my own custom dimax.conf, not generated by dimax\nmap cmd+x send_text all foo\n";
        setup_fake_kitty_config(&dir, Some("include dimax.conf\n"), Some(hand_written));

        let result = with_fake_kitty_env(&dir, ensure_config_written);
        assert!(result.is_err());

        let dimax_conf = std::fs::read_to_string(dir.join("dimax.conf")).unwrap();
        assert_eq!(
            dimax_conf, hand_written,
            "a dimax.conf without the generated marker must be left untouched"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn uninstall_removes_only_managed_files_and_include() {
        let dir = std::env::temp_dir().join(format!("dmx-kitty-test-{}", std::process::id() + 6));
        setup_fake_kitty_config(&dir, Some("font_size 12\n"), None);

        with_fake_kitty_env(&dir, || {
            install().unwrap();
            uninstall().unwrap();
        });

        assert!(!dir.join("dimax.conf").exists());
        assert_eq!(
            std::fs::read_to_string(dir.join("kitty.conf")).unwrap(),
            "font_size 12\n"
        );
        assert!(dir.join("kitty.conf.dimax.bak").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
