//! Auto-installs the `kitty.conf` chord mappings `dimux attach` needs
//! (see `keys.rs`'s module doc for the escape-sequence format) the
//! first time it's run inside a Kitty session, so there's no separate
//! manual setup step for a new install to remember.
//!
//! Runs once per `dimux attach` invocation, best-effort: any failure
//! (not running under Kitty, config directory not writable, etc.) is
//! silently ignored rather than blocking or warning -- this is a
//! convenience, not something the TUI's ability to start should ever
//! depend on. A user who genuinely wants to customize or remove the
//! mappings can freely hand-edit the generated file afterward; this
//! only writes it if it looks untouched (see [`ensure_installed`]'s doc
//! comment for the exact idempotency rule).

use std::io::Write;
use std::path::PathBuf;

/// The full chord table, generated here as the single source of truth
/// for what [`super::keys`] parses AND what gets written to
/// `dimux.conf` -- each entry is `(kitty key combo, dimux tag byte)`.
/// Keeping this as data (rather than hand-copying the escape sequences
/// into a config-file string, which is how the mapping first shipped)
/// means adding a chord to `keys.rs` and to the generated config can
/// never drift out of sync as long as both read from here.
const CHORDS: &[(&str, u8)] = &[
    ("cmd+1", b'1'),
    ("cmd+2", b'2'),
    ("cmd+3", b'3'),
    ("cmd+4", b'4'),
    ("cmd+5", b'5'),
    ("cmd+6", b'6'),
    ("cmd+7", b'7'),
    ("cmd+8", b'8'),
    ("cmd+9", b'9'),
    ("cmd+d", b'd'),
    ("cmd+shift+d", b'D'),
    ("cmd+w", b'w'),
    ("cmd+shift+w", b'W'),
    ("cmd+shift+z", b'Z'),
    ("cmd+h", b'h'),
    ("cmd+j", b'j'),
    ("cmd+k", b'k'),
    ("cmd+l", b'l'),
    ("cmd+t", b't'),
    ("cmd+]", b']'),
    ("cmd+[", b'['),
];

/// Marker comment that opens the generated block -- present so
/// [`ensure_installed`] can tell "this file is exactly what dimux would
/// generate today" apart from "the user has their own `dimux.conf`" (or
/// an older generated version) without needing a separate manifest.
const GENERATED_MARKER: &str = "# --- dimux: generated by `dimux attach`, do not hand-edit ---";

/// Render the full contents of `dimux.conf` (chords + the dedicated
/// `shift+enter` mapping -- see `keys.rs` module doc for why that one's
/// not in [`CHORDS`]) from the tables above.
fn render_dimux_conf() -> String {
    let mut out = String::new();
    out.push_str(GENERATED_MARKER);
    out.push('\n');
    out.push_str(
        "# dimux Cmd-chord forwarding -- lets `dimux attach` recognize Cmd-key\n\
         # chords despite terminals not normally reporting Cmd as a modifier.\n\
         # `all` sends the text regardless of kitty's current keyboard mode,\n\
         # matching how a raw-mode TUI like dimux expects every keystroke to\n\
         # arrive unmodified. See src/tui/keys.rs in the dimux repo for the\n\
         # authoritative escape-sequence table this is generated from.\n\n",
    );
    for (combo, tag) in CHORDS {
        out.push_str(&format!("map {combo} send_text all \\x1b_D{}\\x1b\\\\\n", *tag as char));
    }
    out.push_str(
        "\n# Lets the attach menu's spawn field tell Enter and Shift+Enter apart\n\
         # (otherwise both send the same \\r byte).\n\
         map shift+enter send_text all \\x1b_Ds\\x1b\\\\\n",
    );
    out
}

/// `true` if the current process looks like it's running inside a
/// Kitty window -- `KITTY_WINDOW_ID` is set by Kitty itself for every
/// window it creates, unlike `$TERM`, which a `tmux`/`screen` layer (or
/// this very program) could rewrite.
fn running_under_kitty() -> bool {
    std::env::var_os("KITTY_WINDOW_ID").is_some()
}

/// Kitty's config directory: `$KITTY_CONFIG_DIRECTORY` if the user has
/// overridden it, else the documented default `~/.config/kitty`.
fn kitty_config_dir() -> Option<PathBuf> {
    if let Some(dir) = std::env::var_os("KITTY_CONFIG_DIRECTORY") {
        return Some(PathBuf::from(dir));
    }
    let home = std::env::var("HOME").ok()?;
    Some(PathBuf::from(home).join(".config").join("kitty"))
}

/// Best-effort install of dimux's Kitty chord mappings: writes
/// `<kitty-config-dir>/dimux.conf` (regenerated fresh every time, since
/// it's marked as dimux-owned -- see [`GENERATED_MARKER`]) and adds
/// `include dimux.conf` to the top of `kitty.conf` if not already
/// present. A complete no-op, silently, in any of these cases:
/// - not running under Kitty at all (see [`running_under_kitty`]) --
///   nothing to install into.
/// - `kitty.conf` doesn't exist yet -- a from-scratch Kitty install with
///   no config file at all is unusual enough, and risky enough to get
///   wrong (what should the *rest* of a from-scratch config look like?),
///   that this only ever patches an existing file, never creates one.
/// - `dimux.conf` exists but does NOT start with [`GENERATED_MARKER`] --
///   treated as a user's own hand-written file dimux must never
///   overwrite, even if it happens to share the name. Uses `.starts_with`
///   after a read rather than a separate sentinel/lock file so "did
///   dimux write this" is self-contained in the file itself, inspectable
///   by just opening it.
/// - any I/O error along the way (permissions, disk full, etc.).
///
/// Called once at the top of [`super::run`], before anything else --
/// see that call site for why a failure here must never propagate.
pub fn ensure_installed() {
    let _ = try_ensure_installed();
}

fn try_ensure_installed() -> std::io::Result<()> {
    if !running_under_kitty() {
        return Ok(());
    }
    let Some(config_dir) = kitty_config_dir() else { return Ok(()) };
    let kitty_conf = config_dir.join("kitty.conf");
    if !kitty_conf.is_file() {
        return Ok(());
    }

    let dimux_conf = config_dir.join("dimux.conf");
    let is_ours = match std::fs::read_to_string(&dimux_conf) {
        Ok(existing) => existing.starts_with(GENERATED_MARKER),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => true,
        Err(e) => return Err(e),
    };
    if !is_ours {
        return Ok(());
    }
    std::fs::write(&dimux_conf, render_dimux_conf())?;

    let kitty_conf_text = std::fs::read_to_string(&kitty_conf)?;
    if !kitty_conf_text.lines().any(|line| line.trim() == "include dimux.conf") {
        let mut file = std::fs::OpenOptions::new().append(true).open(&kitty_conf)?;
        // A leading newline in case the existing file has no trailing
        // one, so this never gets glued onto the previous line.
        writeln!(file, "\ninclude dimux.conf")?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Serializes every test in this module that mutates
    /// `KITTY_WINDOW_ID`/`KITTY_CONFIG_DIRECTORY` -- both are
    /// process-global, so two such tests running concurrently (the
    /// default under `cargo test`) could otherwise stomp on each
    /// other's env state mid-test.
    static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    /// `render_dimux_conf`'s output must actually round-trip through
    /// `keys::parse` for every chord byte in [`CHORDS`] -- catches the
    /// exact class of bug this module exists to prevent: the generated
    /// config and the parser silently drifting apart.
    #[test]
    fn render_dimux_conf_produces_chords_keys_parse_recognizes() {
        let rendered = render_dimux_conf();
        for (combo, tag) in CHORDS {
            let expected_line = format!("map {combo} send_text all \\x1b_D{}\\x1b\\\\", *tag as char);
            assert!(rendered.contains(&expected_line), "missing or malformed line for {combo}: {rendered}");

            let bytes = [b"\x1b_D".as_slice(), &[*tag], b"\x1b\\".as_slice()].concat();
            assert_ne!(
                super::super::keys::parse(&bytes),
                super::super::Action::PassThrough,
                "chord for {combo} (tag {}) isn't recognized by keys::parse",
                *tag as char
            );
        }
    }

    #[test]
    fn render_dimux_conf_includes_the_shift_enter_mapping() {
        let rendered = render_dimux_conf();
        assert!(rendered.contains("map shift+enter send_text all \\x1b_Ds\\x1b\\\\"));
    }

    #[test]
    fn render_dimux_conf_starts_with_the_generated_marker() {
        assert!(render_dimux_conf().starts_with(GENERATED_MARKER));
    }

    fn setup_fake_kitty_config(dir: &std::path::Path, kitty_conf_body: Option<&str>, dimux_conf_body: Option<&str>) {
        std::fs::create_dir_all(dir).unwrap();
        if let Some(body) = kitty_conf_body {
            std::fs::write(dir.join("kitty.conf"), body).unwrap();
        }
        if let Some(body) = dimux_conf_body {
            std::fs::write(dir.join("dimux.conf"), body).unwrap();
        }
    }

    /// Runs `try_ensure_installed` against a fake config directory by
    /// setting `KITTY_WINDOW_ID` and `KITTY_CONFIG_DIRECTORY` for the
    /// duration of `f`, then restoring both -- these tests can't run
    /// concurrently with each other (env vars are process-global), so
    /// each acquires this process-wide mutex first. `unsafe` is required
    /// for `set_var`/`remove_var` themselves (Rust 2024 edition); safe in
    /// practice because the mutex serializes every caller.
    fn with_fake_kitty_env<T>(config_dir: &std::path::Path, f: impl FnOnce() -> T) -> T {
        let _guard = ENV_LOCK.lock().unwrap();
        let prev_window_id = std::env::var_os("KITTY_WINDOW_ID");
        let prev_config_dir = std::env::var_os("KITTY_CONFIG_DIRECTORY");
        unsafe {
            std::env::set_var("KITTY_WINDOW_ID", "1");
            std::env::set_var("KITTY_CONFIG_DIRECTORY", config_dir);
        }
        let result = f();
        unsafe {
            match prev_window_id {
                Some(v) => std::env::set_var("KITTY_WINDOW_ID", v),
                None => std::env::remove_var("KITTY_WINDOW_ID"),
            }
            match prev_config_dir {
                Some(v) => std::env::set_var("KITTY_CONFIG_DIRECTORY", v),
                None => std::env::remove_var("KITTY_CONFIG_DIRECTORY"),
            }
        }
        result
    }

    #[test]
    fn ensure_installed_is_a_no_op_when_not_running_under_kitty() {
        let dir = std::env::temp_dir().join(format!("dmx-kitty-test-{}", std::process::id()));
        setup_fake_kitty_config(&dir, Some("# my config\n"), None);

        let _guard = ENV_LOCK.lock().unwrap();
        let prev = std::env::var_os("KITTY_WINDOW_ID");
        unsafe {
            std::env::remove_var("KITTY_WINDOW_ID");
        }
        try_ensure_installed().unwrap();
        unsafe {
            if let Some(v) = prev {
                std::env::set_var("KITTY_WINDOW_ID", v);
            }
        }

        assert!(!dir.join("dimux.conf").exists(), "should not write anything when not under Kitty");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ensure_installed_does_nothing_if_kitty_conf_does_not_exist() {
        let dir = std::env::temp_dir().join(format!("dmx-kitty-test-{}", std::process::id() + 1));
        setup_fake_kitty_config(&dir, None, None);

        with_fake_kitty_env(&dir, || try_ensure_installed().unwrap());

        assert!(!dir.join("dimux.conf").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ensure_installed_writes_dimux_conf_and_patches_kitty_conf() {
        let dir = std::env::temp_dir().join(format!("dmx-kitty-test-{}", std::process::id() + 2));
        setup_fake_kitty_config(&dir, Some("# my existing config\nfont_size 12\n"), None);

        with_fake_kitty_env(&dir, || try_ensure_installed().unwrap());

        let dimux_conf = std::fs::read_to_string(dir.join("dimux.conf")).unwrap();
        assert!(dimux_conf.starts_with(GENERATED_MARKER));
        assert!(dimux_conf.contains("map cmd+shift+z"));

        let kitty_conf = std::fs::read_to_string(dir.join("kitty.conf")).unwrap();
        assert!(kitty_conf.contains("font_size 12"), "existing content must be preserved");
        assert!(kitty_conf.lines().any(|l| l.trim() == "include dimux.conf"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ensure_installed_does_not_duplicate_the_include_line_on_a_second_run() {
        let dir = std::env::temp_dir().join(format!("dmx-kitty-test-{}", std::process::id() + 3));
        setup_fake_kitty_config(&dir, Some("# my config\n"), None);

        with_fake_kitty_env(&dir, || {
            try_ensure_installed().unwrap();
            try_ensure_installed().unwrap();
        });

        let kitty_conf = std::fs::read_to_string(dir.join("kitty.conf")).unwrap();
        let include_count = kitty_conf.lines().filter(|l| l.trim() == "include dimux.conf").count();
        assert_eq!(include_count, 1, "the include line must not be duplicated across repeated runs");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ensure_installed_refreshes_a_previously_generated_dimux_conf() {
        let dir = std::env::temp_dir().join(format!("dmx-kitty-test-{}", std::process::id() + 4));
        let stale_generated = format!("{GENERATED_MARKER}\nmap cmd+1 send_text all \\x1b_D1\\x1b\\\\\n");
        setup_fake_kitty_config(&dir, Some("include dimux.conf\n"), Some(&stale_generated));

        with_fake_kitty_env(&dir, || try_ensure_installed().unwrap());

        let dimux_conf = std::fs::read_to_string(dir.join("dimux.conf")).unwrap();
        assert!(dimux_conf.contains("map cmd+shift+z"), "should have been regenerated with the full current table");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ensure_installed_never_overwrites_a_hand_written_dimux_conf() {
        let dir = std::env::temp_dir().join(format!("dmx-kitty-test-{}", std::process::id() + 5));
        let hand_written = "# my own custom dimux.conf, not generated by dimux\nmap cmd+x send_text all foo\n";
        setup_fake_kitty_config(&dir, Some("include dimux.conf\n"), Some(hand_written));

        with_fake_kitty_env(&dir, || try_ensure_installed().unwrap());

        let dimux_conf = std::fs::read_to_string(dir.join("dimux.conf")).unwrap();
        assert_eq!(dimux_conf, hand_written, "a dimux.conf without the generated marker must be left untouched");

        let _ = std::fs::remove_dir_all(&dir);
    }
}
